from enum import Enum


class TaxonomyConfig(str, Enum):
    INNER_NODES_ANY = "INNER_NODES_ANY"
    INNER_NODES_PESSIMISTIC = "INNER_NODES_PESSIMISTIC"
    INNER_NODES_OPTIMISTIC = "INNER_NODES_OPTIMISTIC"
    INNER_NODES_AVERAGE = "INNER_NODES_AVERAGE"
    NO_INNERNODES = "NO_INNERNODES"
